#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VuVanHoa_nenmong")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_lop_dat(tbl_lop_dat instance);
    partial void Updatetbl_lop_dat(tbl_lop_dat instance);
    partial void Deletetbl_lop_dat(tbl_lop_dat instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VuVanHoa_nenmongConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_lop_dat> tbl_lop_dats
		{
			get
			{
				return this.GetTable<tbl_lop_dat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lop_dat")]
	public partial class tbl_lop_dat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lop_dat;
		
		private string _MaLopDat;
		
		private System.Nullable<double> _chieuday;
		
		private System.Nullable<byte> _n;
		
		private string _loaidat;
		
		private string _trangthai;
		
		private System.Nullable<double> _dungtrongrieng;
		
		private System.Nullable<int> _modundanhoi;
		
		private System.Nullable<int> _gocmasat;
		
		private System.Nullable<int> _doroi;
		
		private System.Nullable<int> _suckhangxuyen;
		
		private System.Nullable<int> _is_delete;
		
		private System.Nullable<double> _k;
		
		private System.Nullable<double> _alpha;
		
		private System.Nullable<int> _vitritrentrudiachat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lop_datChanging(int value);
    partial void Onid_lop_datChanged();
    partial void OnMaLopDatChanging(string value);
    partial void OnMaLopDatChanged();
    partial void OnchieudayChanging(System.Nullable<double> value);
    partial void OnchieudayChanged();
    partial void OnnChanging(System.Nullable<byte> value);
    partial void OnnChanged();
    partial void OnloaidatChanging(string value);
    partial void OnloaidatChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OndungtrongriengChanging(System.Nullable<double> value);
    partial void OndungtrongriengChanged();
    partial void OnmodundanhoiChanging(System.Nullable<int> value);
    partial void OnmodundanhoiChanged();
    partial void OngocmasatChanging(System.Nullable<int> value);
    partial void OngocmasatChanged();
    partial void OndoroiChanging(System.Nullable<int> value);
    partial void OndoroiChanged();
    partial void OnsuckhangxuyenChanging(System.Nullable<int> value);
    partial void OnsuckhangxuyenChanged();
    partial void Onis_deleteChanging(System.Nullable<int> value);
    partial void Onis_deleteChanged();
    partial void OnkChanging(System.Nullable<double> value);
    partial void OnkChanged();
    partial void OnalphaChanging(System.Nullable<double> value);
    partial void OnalphaChanged();
    partial void OnvitritrentrudiachatChanging(System.Nullable<int> value);
    partial void OnvitritrentrudiachatChanged();
    #endregion
		
		public tbl_lop_dat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lop_dat", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_lop_dat
		{
			get
			{
				return this._id_lop_dat;
			}
			set
			{
				if ((this._id_lop_dat != value))
				{
					this.Onid_lop_datChanging(value);
					this.SendPropertyChanging();
					this._id_lop_dat = value;
					this.SendPropertyChanged("id_lop_dat");
					this.Onid_lop_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopDat", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLopDat
		{
			get
			{
				return this._MaLopDat;
			}
			set
			{
				if ((this._MaLopDat != value))
				{
					this.OnMaLopDatChanging(value);
					this.SendPropertyChanging();
					this._MaLopDat = value;
					this.SendPropertyChanged("MaLopDat");
					this.OnMaLopDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chieuday", DbType="Float")]
		public System.Nullable<double> chieuday
		{
			get
			{
				return this._chieuday;
			}
			set
			{
				if ((this._chieuday != value))
				{
					this.OnchieudayChanging(value);
					this.SendPropertyChanging();
					this._chieuday = value;
					this.SendPropertyChanged("chieuday");
					this.OnchieudayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n", DbType="TinyInt")]
		public System.Nullable<byte> n
		{
			get
			{
				return this._n;
			}
			set
			{
				if ((this._n != value))
				{
					this.OnnChanging(value);
					this.SendPropertyChanging();
					this._n = value;
					this.SendPropertyChanged("n");
					this.OnnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaidat", DbType="NVarChar(50)")]
		public string loaidat
		{
			get
			{
				return this._loaidat;
			}
			set
			{
				if ((this._loaidat != value))
				{
					this.OnloaidatChanging(value);
					this.SendPropertyChanging();
					this._loaidat = value;
					this.SendPropertyChanged("loaidat");
					this.OnloaidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dungtrongrieng", DbType="Float")]
		public System.Nullable<double> dungtrongrieng
		{
			get
			{
				return this._dungtrongrieng;
			}
			set
			{
				if ((this._dungtrongrieng != value))
				{
					this.OndungtrongriengChanging(value);
					this.SendPropertyChanging();
					this._dungtrongrieng = value;
					this.SendPropertyChanged("dungtrongrieng");
					this.OndungtrongriengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modundanhoi", DbType="Int")]
		public System.Nullable<int> modundanhoi
		{
			get
			{
				return this._modundanhoi;
			}
			set
			{
				if ((this._modundanhoi != value))
				{
					this.OnmodundanhoiChanging(value);
					this.SendPropertyChanging();
					this._modundanhoi = value;
					this.SendPropertyChanged("modundanhoi");
					this.OnmodundanhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gocmasat", DbType="Int")]
		public System.Nullable<int> gocmasat
		{
			get
			{
				return this._gocmasat;
			}
			set
			{
				if ((this._gocmasat != value))
				{
					this.OngocmasatChanging(value);
					this.SendPropertyChanging();
					this._gocmasat = value;
					this.SendPropertyChanged("gocmasat");
					this.OngocmasatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doroi", DbType="Int")]
		public System.Nullable<int> doroi
		{
			get
			{
				return this._doroi;
			}
			set
			{
				if ((this._doroi != value))
				{
					this.OndoroiChanging(value);
					this.SendPropertyChanging();
					this._doroi = value;
					this.SendPropertyChanged("doroi");
					this.OndoroiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suckhangxuyen", DbType="Int")]
		public System.Nullable<int> suckhangxuyen
		{
			get
			{
				return this._suckhangxuyen;
			}
			set
			{
				if ((this._suckhangxuyen != value))
				{
					this.OnsuckhangxuyenChanging(value);
					this.SendPropertyChanging();
					this._suckhangxuyen = value;
					this.SendPropertyChanged("suckhangxuyen");
					this.OnsuckhangxuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_delete", DbType="Int")]
		public System.Nullable<int> is_delete
		{
			get
			{
				return this._is_delete;
			}
			set
			{
				if ((this._is_delete != value))
				{
					this.Onis_deleteChanging(value);
					this.SendPropertyChanging();
					this._is_delete = value;
					this.SendPropertyChanged("is_delete");
					this.Onis_deleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k", DbType="Float")]
		public System.Nullable<double> k
		{
			get
			{
				return this._k;
			}
			set
			{
				if ((this._k != value))
				{
					this.OnkChanging(value);
					this.SendPropertyChanging();
					this._k = value;
					this.SendPropertyChanged("k");
					this.OnkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha", DbType="Float")]
		public System.Nullable<double> alpha
		{
			get
			{
				return this._alpha;
			}
			set
			{
				if ((this._alpha != value))
				{
					this.OnalphaChanging(value);
					this.SendPropertyChanging();
					this._alpha = value;
					this.SendPropertyChanged("alpha");
					this.OnalphaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitritrentrudiachat", DbType="Int")]
		public System.Nullable<int> vitritrentrudiachat
		{
			get
			{
				return this._vitritrentrudiachat;
			}
			set
			{
				if ((this._vitritrentrudiachat != value))
				{
					this.OnvitritrentrudiachatChanging(value);
					this.SendPropertyChanging();
					this._vitritrentrudiachat = value;
					this.SendPropertyChanged("vitritrentrudiachat");
					this.OnvitritrentrudiachatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
