#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_Hoa_Yambi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VuVanHoa_nenmong")]
	public partial class VuVanHoa_DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_betong(tbl_betong instance);
    partial void Updatetbl_betong(tbl_betong instance);
    partial void Deletetbl_betong(tbl_betong instance);
    partial void Inserttbl_coc(tbl_coc instance);
    partial void Updatetbl_coc(tbl_coc instance);
    partial void Deletetbl_coc(tbl_coc instance);
    partial void Inserttbl_cot_thep(tbl_cot_thep instance);
    partial void Updatetbl_cot_thep(tbl_cot_thep instance);
    partial void Deletetbl_cot_thep(tbl_cot_thep instance);
    partial void Inserttbl_lop_dat(tbl_lop_dat instance);
    partial void Updatetbl_lop_dat(tbl_lop_dat instance);
    partial void Deletetbl_lop_dat(tbl_lop_dat instance);
    partial void Inserttbl_User(tbl_User instance);
    partial void Updatetbl_User(tbl_User instance);
    partial void Deletetbl_User(tbl_User instance);
    #endregion
		
		public VuVanHoa_DatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VuVanHoa_nenmongConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_betong> tbl_betongs
		{
			get
			{
				return this.GetTable<tbl_betong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_coc> tbl_cocs
		{
			get
			{
				return this.GetTable<tbl_coc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_cot_thep> tbl_cot_theps
		{
			get
			{
				return this.GetTable<tbl_cot_thep>();
			}
		}
		
		public System.Data.Linq.Table<tbl_daimong> tbl_daimongs
		{
			get
			{
				return this.GetTable<tbl_daimong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lop_dat> tbl_lop_dats
		{
			get
			{
				return this.GetTable<tbl_lop_dat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_User> tbl_Users
		{
			get
			{
				return this.GetTable<tbl_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_betong")]
	public partial class tbl_betong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_betong;
		
		private string _mabetong;
		
		private string _tenbetong;
		
		private System.Nullable<double> _rb;
		
		private System.Nullable<double> _rbt;
		
		private System.Nullable<double> _eb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_betongChanging(int value);
    partial void Onid_betongChanged();
    partial void OnmabetongChanging(string value);
    partial void OnmabetongChanged();
    partial void OntenbetongChanging(string value);
    partial void OntenbetongChanged();
    partial void OnrbChanging(System.Nullable<double> value);
    partial void OnrbChanged();
    partial void OnrbtChanging(System.Nullable<double> value);
    partial void OnrbtChanged();
    partial void OnebChanging(System.Nullable<double> value);
    partial void OnebChanged();
    #endregion
		
		public tbl_betong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_betong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_betong
		{
			get
			{
				return this._id_betong;
			}
			set
			{
				if ((this._id_betong != value))
				{
					this.Onid_betongChanging(value);
					this.SendPropertyChanging();
					this._id_betong = value;
					this.SendPropertyChanged("id_betong");
					this.Onid_betongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabetong", DbType="VarChar(35)")]
		public string mabetong
		{
			get
			{
				return this._mabetong;
			}
			set
			{
				if ((this._mabetong != value))
				{
					this.OnmabetongChanging(value);
					this.SendPropertyChanging();
					this._mabetong = value;
					this.SendPropertyChanged("mabetong");
					this.OnmabetongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbetong", DbType="VarChar(35)")]
		public string tenbetong
		{
			get
			{
				return this._tenbetong;
			}
			set
			{
				if ((this._tenbetong != value))
				{
					this.OntenbetongChanging(value);
					this.SendPropertyChanging();
					this._tenbetong = value;
					this.SendPropertyChanged("tenbetong");
					this.OntenbetongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rb", DbType="Float")]
		public System.Nullable<double> rb
		{
			get
			{
				return this._rb;
			}
			set
			{
				if ((this._rb != value))
				{
					this.OnrbChanging(value);
					this.SendPropertyChanging();
					this._rb = value;
					this.SendPropertyChanged("rb");
					this.OnrbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rbt", DbType="Float")]
		public System.Nullable<double> rbt
		{
			get
			{
				return this._rbt;
			}
			set
			{
				if ((this._rbt != value))
				{
					this.OnrbtChanging(value);
					this.SendPropertyChanging();
					this._rbt = value;
					this.SendPropertyChanged("rbt");
					this.OnrbtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eb", DbType="Float")]
		public System.Nullable<double> eb
		{
			get
			{
				return this._eb;
			}
			set
			{
				if ((this._eb != value))
				{
					this.OnebChanging(value);
					this.SendPropertyChanging();
					this._eb = value;
					this.SendPropertyChanged("eb");
					this.OnebChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_coc")]
	public partial class tbl_coc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_coc;
		
		private string _MaCoc;
		
		private string _TenCoc;
		
		private string _DoDai;
		
		private System.Nullable<double> _DuongKinhCoc;
		
		private System.Nullable<byte> _SoThanhThep;
		
		private System.Nullable<byte> _DuongKinhThep;
		
		private System.Nullable<int> _IDCotThep;
		
		private System.Nullable<int> _id_betong;
		
		private System.Nullable<double> _SucChiuTai;
		
		private System.Nullable<int> _is_deleted;
		
		private System.Nullable<double> _ChuVi_TD;
		
		private System.Nullable<double> _DienTich_TD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cocChanging(int value);
    partial void Onid_cocChanged();
    partial void OnMaCocChanging(string value);
    partial void OnMaCocChanged();
    partial void OnTenCocChanging(string value);
    partial void OnTenCocChanged();
    partial void OnDoDaiChanging(string value);
    partial void OnDoDaiChanged();
    partial void OnDuongKinhCocChanging(System.Nullable<double> value);
    partial void OnDuongKinhCocChanged();
    partial void OnSoThanhThepChanging(System.Nullable<byte> value);
    partial void OnSoThanhThepChanged();
    partial void OnDuongKinhThepChanging(System.Nullable<byte> value);
    partial void OnDuongKinhThepChanged();
    partial void OnIDCotThepChanging(System.Nullable<int> value);
    partial void OnIDCotThepChanged();
    partial void Onid_betongChanging(System.Nullable<int> value);
    partial void Onid_betongChanged();
    partial void OnSucChiuTaiChanging(System.Nullable<double> value);
    partial void OnSucChiuTaiChanged();
    partial void Onis_deletedChanging(System.Nullable<int> value);
    partial void Onis_deletedChanged();
    partial void OnChuVi_TDChanging(System.Nullable<double> value);
    partial void OnChuVi_TDChanged();
    partial void OnDienTich_TDChanging(System.Nullable<double> value);
    partial void OnDienTich_TDChanged();
    #endregion
		
		public tbl_coc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_coc", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_coc
		{
			get
			{
				return this._id_coc;
			}
			set
			{
				if ((this._id_coc != value))
				{
					this.Onid_cocChanging(value);
					this.SendPropertyChanging();
					this._id_coc = value;
					this.SendPropertyChanged("id_coc");
					this.Onid_cocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCoc", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCoc
		{
			get
			{
				return this._MaCoc;
			}
			set
			{
				if ((this._MaCoc != value))
				{
					this.OnMaCocChanging(value);
					this.SendPropertyChanging();
					this._MaCoc = value;
					this.SendPropertyChanged("MaCoc");
					this.OnMaCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCoc", DbType="NVarChar(35)")]
		public string TenCoc
		{
			get
			{
				return this._TenCoc;
			}
			set
			{
				if ((this._TenCoc != value))
				{
					this.OnTenCocChanging(value);
					this.SendPropertyChanging();
					this._TenCoc = value;
					this.SendPropertyChanged("TenCoc");
					this.OnTenCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoDai", DbType="NChar(10)")]
		public string DoDai
		{
			get
			{
				return this._DoDai;
			}
			set
			{
				if ((this._DoDai != value))
				{
					this.OnDoDaiChanging(value);
					this.SendPropertyChanging();
					this._DoDai = value;
					this.SendPropertyChanged("DoDai");
					this.OnDoDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongKinhCoc", DbType="Float")]
		public System.Nullable<double> DuongKinhCoc
		{
			get
			{
				return this._DuongKinhCoc;
			}
			set
			{
				if ((this._DuongKinhCoc != value))
				{
					this.OnDuongKinhCocChanging(value);
					this.SendPropertyChanging();
					this._DuongKinhCoc = value;
					this.SendPropertyChanged("DuongKinhCoc");
					this.OnDuongKinhCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThanhThep", DbType="TinyInt")]
		public System.Nullable<byte> SoThanhThep
		{
			get
			{
				return this._SoThanhThep;
			}
			set
			{
				if ((this._SoThanhThep != value))
				{
					this.OnSoThanhThepChanging(value);
					this.SendPropertyChanging();
					this._SoThanhThep = value;
					this.SendPropertyChanged("SoThanhThep");
					this.OnSoThanhThepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongKinhThep", DbType="TinyInt")]
		public System.Nullable<byte> DuongKinhThep
		{
			get
			{
				return this._DuongKinhThep;
			}
			set
			{
				if ((this._DuongKinhThep != value))
				{
					this.OnDuongKinhThepChanging(value);
					this.SendPropertyChanging();
					this._DuongKinhThep = value;
					this.SendPropertyChanged("DuongKinhThep");
					this.OnDuongKinhThepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCotThep", DbType="Int")]
		public System.Nullable<int> IDCotThep
		{
			get
			{
				return this._IDCotThep;
			}
			set
			{
				if ((this._IDCotThep != value))
				{
					this.OnIDCotThepChanging(value);
					this.SendPropertyChanging();
					this._IDCotThep = value;
					this.SendPropertyChanged("IDCotThep");
					this.OnIDCotThepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_betong", DbType="Int")]
		public System.Nullable<int> id_betong
		{
			get
			{
				return this._id_betong;
			}
			set
			{
				if ((this._id_betong != value))
				{
					this.Onid_betongChanging(value);
					this.SendPropertyChanging();
					this._id_betong = value;
					this.SendPropertyChanged("id_betong");
					this.Onid_betongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChiuTai", DbType="Float")]
		public System.Nullable<double> SucChiuTai
		{
			get
			{
				return this._SucChiuTai;
			}
			set
			{
				if ((this._SucChiuTai != value))
				{
					this.OnSucChiuTaiChanging(value);
					this.SendPropertyChanging();
					this._SucChiuTai = value;
					this.SendPropertyChanged("SucChiuTai");
					this.OnSucChiuTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Int")]
		public System.Nullable<int> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuVi_TD", DbType="Float")]
		public System.Nullable<double> ChuVi_TD
		{
			get
			{
				return this._ChuVi_TD;
			}
			set
			{
				if ((this._ChuVi_TD != value))
				{
					this.OnChuVi_TDChanging(value);
					this.SendPropertyChanging();
					this._ChuVi_TD = value;
					this.SendPropertyChanged("ChuVi_TD");
					this.OnChuVi_TDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich_TD", DbType="Float")]
		public System.Nullable<double> DienTich_TD
		{
			get
			{
				return this._DienTich_TD;
			}
			set
			{
				if ((this._DienTich_TD != value))
				{
					this.OnDienTich_TDChanging(value);
					this.SendPropertyChanging();
					this._DienTich_TD = value;
					this.SendPropertyChanged("DienTich_TD");
					this.OnDienTich_TDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cot_thep")]
	public partial class tbl_cot_thep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCotThep;
		
		private string _MaCotThep;
		
		private string _TenCotThep;
		
		private System.Nullable<double> _Rs;
		
		private System.Nullable<double> _Rsc;
		
		private System.Nullable<double> _Es;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCotThepChanging(int value);
    partial void OnIDCotThepChanged();
    partial void OnMaCotThepChanging(string value);
    partial void OnMaCotThepChanged();
    partial void OnTenCotThepChanging(string value);
    partial void OnTenCotThepChanged();
    partial void OnRsChanging(System.Nullable<double> value);
    partial void OnRsChanged();
    partial void OnRscChanging(System.Nullable<double> value);
    partial void OnRscChanged();
    partial void OnEsChanging(System.Nullable<double> value);
    partial void OnEsChanged();
    #endregion
		
		public tbl_cot_thep()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCotThep", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCotThep
		{
			get
			{
				return this._IDCotThep;
			}
			set
			{
				if ((this._IDCotThep != value))
				{
					this.OnIDCotThepChanging(value);
					this.SendPropertyChanging();
					this._IDCotThep = value;
					this.SendPropertyChanged("IDCotThep");
					this.OnIDCotThepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCotThep", DbType="VarChar(35)")]
		public string MaCotThep
		{
			get
			{
				return this._MaCotThep;
			}
			set
			{
				if ((this._MaCotThep != value))
				{
					this.OnMaCotThepChanging(value);
					this.SendPropertyChanging();
					this._MaCotThep = value;
					this.SendPropertyChanged("MaCotThep");
					this.OnMaCotThepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCotThep", DbType="VarChar(35)")]
		public string TenCotThep
		{
			get
			{
				return this._TenCotThep;
			}
			set
			{
				if ((this._TenCotThep != value))
				{
					this.OnTenCotThepChanging(value);
					this.SendPropertyChanging();
					this._TenCotThep = value;
					this.SendPropertyChanged("TenCotThep");
					this.OnTenCotThepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rs", DbType="Float")]
		public System.Nullable<double> Rs
		{
			get
			{
				return this._Rs;
			}
			set
			{
				if ((this._Rs != value))
				{
					this.OnRsChanging(value);
					this.SendPropertyChanging();
					this._Rs = value;
					this.SendPropertyChanged("Rs");
					this.OnRsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rsc", DbType="Float")]
		public System.Nullable<double> Rsc
		{
			get
			{
				return this._Rsc;
			}
			set
			{
				if ((this._Rsc != value))
				{
					this.OnRscChanging(value);
					this.SendPropertyChanging();
					this._Rsc = value;
					this.SendPropertyChanged("Rsc");
					this.OnRscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Es", DbType="Float")]
		public System.Nullable<double> Es
		{
			get
			{
				return this._Es;
			}
			set
			{
				if ((this._Es != value))
				{
					this.OnEsChanging(value);
					this.SendPropertyChanging();
					this._Es = value;
					this.SendPropertyChanged("Es");
					this.OnEsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_daimong")]
	public partial class tbl_daimong
	{
		
		private System.Nullable<double> _Ldai;
		
		private System.Nullable<double> _Bdai;
		
		public tbl_daimong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ldai", DbType="Float")]
		public System.Nullable<double> Ldai
		{
			get
			{
				return this._Ldai;
			}
			set
			{
				if ((this._Ldai != value))
				{
					this._Ldai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bdai", DbType="Float")]
		public System.Nullable<double> Bdai
		{
			get
			{
				return this._Bdai;
			}
			set
			{
				if ((this._Bdai != value))
				{
					this._Bdai = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lop_dat")]
	public partial class tbl_lop_dat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lop_dat;
		
		private string _MaLopDat;
		
		private System.Nullable<double> _chieuday;
		
		private System.Nullable<byte> _n;
		
		private string _loaidat;
		
		private string _trangthai;
		
		private System.Nullable<double> _dungtrongrieng;
		
		private System.Nullable<int> _modundanhoi;
		
		private System.Nullable<int> _gocmasat;
		
		private System.Nullable<int> _doroi;
		
		private System.Nullable<int> _suckhangxuyen;
		
		private System.Nullable<int> _is_delete;
		
		private System.Nullable<double> _k;
		
		private System.Nullable<double> _alpha;
		
		private System.Nullable<int> _vitritrentrudiachat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lop_datChanging(int value);
    partial void Onid_lop_datChanged();
    partial void OnMaLopDatChanging(string value);
    partial void OnMaLopDatChanged();
    partial void OnchieudayChanging(System.Nullable<double> value);
    partial void OnchieudayChanged();
    partial void OnnChanging(System.Nullable<byte> value);
    partial void OnnChanged();
    partial void OnloaidatChanging(string value);
    partial void OnloaidatChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OndungtrongriengChanging(System.Nullable<double> value);
    partial void OndungtrongriengChanged();
    partial void OnmodundanhoiChanging(System.Nullable<int> value);
    partial void OnmodundanhoiChanged();
    partial void OngocmasatChanging(System.Nullable<int> value);
    partial void OngocmasatChanged();
    partial void OndoroiChanging(System.Nullable<int> value);
    partial void OndoroiChanged();
    partial void OnsuckhangxuyenChanging(System.Nullable<int> value);
    partial void OnsuckhangxuyenChanged();
    partial void Onis_deleteChanging(System.Nullable<int> value);
    partial void Onis_deleteChanged();
    partial void OnkChanging(System.Nullable<double> value);
    partial void OnkChanged();
    partial void OnalphaChanging(System.Nullable<double> value);
    partial void OnalphaChanged();
    partial void OnvitritrentrudiachatChanging(System.Nullable<int> value);
    partial void OnvitritrentrudiachatChanged();
    #endregion
		
		public tbl_lop_dat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lop_dat", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_lop_dat
		{
			get
			{
				return this._id_lop_dat;
			}
			set
			{
				if ((this._id_lop_dat != value))
				{
					this.Onid_lop_datChanging(value);
					this.SendPropertyChanging();
					this._id_lop_dat = value;
					this.SendPropertyChanged("id_lop_dat");
					this.Onid_lop_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopDat", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLopDat
		{
			get
			{
				return this._MaLopDat;
			}
			set
			{
				if ((this._MaLopDat != value))
				{
					this.OnMaLopDatChanging(value);
					this.SendPropertyChanging();
					this._MaLopDat = value;
					this.SendPropertyChanged("MaLopDat");
					this.OnMaLopDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chieuday", DbType="Float")]
		public System.Nullable<double> chieuday
		{
			get
			{
				return this._chieuday;
			}
			set
			{
				if ((this._chieuday != value))
				{
					this.OnchieudayChanging(value);
					this.SendPropertyChanging();
					this._chieuday = value;
					this.SendPropertyChanged("chieuday");
					this.OnchieudayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n", DbType="TinyInt")]
		public System.Nullable<byte> n
		{
			get
			{
				return this._n;
			}
			set
			{
				if ((this._n != value))
				{
					this.OnnChanging(value);
					this.SendPropertyChanging();
					this._n = value;
					this.SendPropertyChanged("n");
					this.OnnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaidat", DbType="NVarChar(50)")]
		public string loaidat
		{
			get
			{
				return this._loaidat;
			}
			set
			{
				if ((this._loaidat != value))
				{
					this.OnloaidatChanging(value);
					this.SendPropertyChanging();
					this._loaidat = value;
					this.SendPropertyChanged("loaidat");
					this.OnloaidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dungtrongrieng", DbType="Float")]
		public System.Nullable<double> dungtrongrieng
		{
			get
			{
				return this._dungtrongrieng;
			}
			set
			{
				if ((this._dungtrongrieng != value))
				{
					this.OndungtrongriengChanging(value);
					this.SendPropertyChanging();
					this._dungtrongrieng = value;
					this.SendPropertyChanged("dungtrongrieng");
					this.OndungtrongriengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modundanhoi", DbType="Int")]
		public System.Nullable<int> modundanhoi
		{
			get
			{
				return this._modundanhoi;
			}
			set
			{
				if ((this._modundanhoi != value))
				{
					this.OnmodundanhoiChanging(value);
					this.SendPropertyChanging();
					this._modundanhoi = value;
					this.SendPropertyChanged("modundanhoi");
					this.OnmodundanhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gocmasat", DbType="Int")]
		public System.Nullable<int> gocmasat
		{
			get
			{
				return this._gocmasat;
			}
			set
			{
				if ((this._gocmasat != value))
				{
					this.OngocmasatChanging(value);
					this.SendPropertyChanging();
					this._gocmasat = value;
					this.SendPropertyChanged("gocmasat");
					this.OngocmasatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doroi", DbType="Int")]
		public System.Nullable<int> doroi
		{
			get
			{
				return this._doroi;
			}
			set
			{
				if ((this._doroi != value))
				{
					this.OndoroiChanging(value);
					this.SendPropertyChanging();
					this._doroi = value;
					this.SendPropertyChanged("doroi");
					this.OndoroiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suckhangxuyen", DbType="Int")]
		public System.Nullable<int> suckhangxuyen
		{
			get
			{
				return this._suckhangxuyen;
			}
			set
			{
				if ((this._suckhangxuyen != value))
				{
					this.OnsuckhangxuyenChanging(value);
					this.SendPropertyChanging();
					this._suckhangxuyen = value;
					this.SendPropertyChanged("suckhangxuyen");
					this.OnsuckhangxuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_delete", DbType="Int")]
		public System.Nullable<int> is_delete
		{
			get
			{
				return this._is_delete;
			}
			set
			{
				if ((this._is_delete != value))
				{
					this.Onis_deleteChanging(value);
					this.SendPropertyChanging();
					this._is_delete = value;
					this.SendPropertyChanged("is_delete");
					this.Onis_deleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k", DbType="Float")]
		public System.Nullable<double> k
		{
			get
			{
				return this._k;
			}
			set
			{
				if ((this._k != value))
				{
					this.OnkChanging(value);
					this.SendPropertyChanging();
					this._k = value;
					this.SendPropertyChanged("k");
					this.OnkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha", DbType="Float")]
		public System.Nullable<double> alpha
		{
			get
			{
				return this._alpha;
			}
			set
			{
				if ((this._alpha != value))
				{
					this.OnalphaChanging(value);
					this.SendPropertyChanging();
					this._alpha = value;
					this.SendPropertyChanged("alpha");
					this.OnalphaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitritrentrudiachat", DbType="Int")]
		public System.Nullable<int> vitritrentrudiachat
		{
			get
			{
				return this._vitritrentrudiachat;
			}
			set
			{
				if ((this._vitritrentrudiachat != value))
				{
					this.OnvitritrentrudiachatChanging(value);
					this.SendPropertyChanging();
					this._vitritrentrudiachat = value;
					this.SendPropertyChanged("vitritrentrudiachat");
					this.OnvitritrentrudiachatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User")]
	public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _Ten;
		
		private string _SoDienThoai;
		
		private string _MaCoc;
		
		private string _MaDai;
		
		private System.Nullable<double> _Spt;
		
		private System.Nullable<double> _Cpt;
		
		private string _DiaChat;
		
		private System.Nullable<double> _No;
		
		private System.Nullable<double> _Mo;
		
		private System.Nullable<double> _Qo;
		
		private System.Nullable<double> _b_cot;
		
		private System.Nullable<double> _h_cot;
		
		private System.Nullable<double> _h_dai;
		
		private System.Nullable<double> _Bdai;
		
		private System.Nullable<double> _Ldai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnMaCocChanging(string value);
    partial void OnMaCocChanged();
    partial void OnMaDaiChanging(string value);
    partial void OnMaDaiChanged();
    partial void OnSptChanging(System.Nullable<double> value);
    partial void OnSptChanged();
    partial void OnCptChanging(System.Nullable<double> value);
    partial void OnCptChanged();
    partial void OnDiaChatChanging(string value);
    partial void OnDiaChatChanged();
    partial void OnNoChanging(System.Nullable<double> value);
    partial void OnNoChanged();
    partial void OnMoChanging(System.Nullable<double> value);
    partial void OnMoChanged();
    partial void OnQoChanging(System.Nullable<double> value);
    partial void OnQoChanged();
    partial void Onb_cotChanging(System.Nullable<double> value);
    partial void Onb_cotChanged();
    partial void Onh_cotChanging(System.Nullable<double> value);
    partial void Onh_cotChanged();
    partial void Onh_daiChanging(System.Nullable<double> value);
    partial void Onh_daiChanged();
    partial void OnBdaiChanging(System.Nullable<double> value);
    partial void OnBdaiChanged();
    partial void OnLdaiChanging(System.Nullable<double> value);
    partial void OnLdaiChanged();
    #endregion
		
		public tbl_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(250)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(25)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCoc", DbType="VarChar(20)")]
		public string MaCoc
		{
			get
			{
				return this._MaCoc;
			}
			set
			{
				if ((this._MaCoc != value))
				{
					this.OnMaCocChanging(value);
					this.SendPropertyChanging();
					this._MaCoc = value;
					this.SendPropertyChanged("MaCoc");
					this.OnMaCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDai", DbType="VarChar(35)")]
		public string MaDai
		{
			get
			{
				return this._MaDai;
			}
			set
			{
				if ((this._MaDai != value))
				{
					this.OnMaDaiChanging(value);
					this.SendPropertyChanging();
					this._MaDai = value;
					this.SendPropertyChanged("MaDai");
					this.OnMaDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spt", DbType="Float")]
		public System.Nullable<double> Spt
		{
			get
			{
				return this._Spt;
			}
			set
			{
				if ((this._Spt != value))
				{
					this.OnSptChanging(value);
					this.SendPropertyChanging();
					this._Spt = value;
					this.SendPropertyChanged("Spt");
					this.OnSptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cpt", DbType="Float")]
		public System.Nullable<double> Cpt
		{
			get
			{
				return this._Cpt;
			}
			set
			{
				if ((this._Cpt != value))
				{
					this.OnCptChanging(value);
					this.SendPropertyChanging();
					this._Cpt = value;
					this.SendPropertyChanged("Cpt");
					this.OnCptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChat", DbType="VarChar(50)")]
		public string DiaChat
		{
			get
			{
				return this._DiaChat;
			}
			set
			{
				if ((this._DiaChat != value))
				{
					this.OnDiaChatChanging(value);
					this.SendPropertyChanging();
					this._DiaChat = value;
					this.SendPropertyChanged("DiaChat");
					this.OnDiaChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Float")]
		public System.Nullable<double> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mo", DbType="Float")]
		public System.Nullable<double> Mo
		{
			get
			{
				return this._Mo;
			}
			set
			{
				if ((this._Mo != value))
				{
					this.OnMoChanging(value);
					this.SendPropertyChanging();
					this._Mo = value;
					this.SendPropertyChanged("Mo");
					this.OnMoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qo", DbType="Float")]
		public System.Nullable<double> Qo
		{
			get
			{
				return this._Qo;
			}
			set
			{
				if ((this._Qo != value))
				{
					this.OnQoChanging(value);
					this.SendPropertyChanging();
					this._Qo = value;
					this.SendPropertyChanged("Qo");
					this.OnQoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_cot", DbType="Float")]
		public System.Nullable<double> b_cot
		{
			get
			{
				return this._b_cot;
			}
			set
			{
				if ((this._b_cot != value))
				{
					this.Onb_cotChanging(value);
					this.SendPropertyChanging();
					this._b_cot = value;
					this.SendPropertyChanged("b_cot");
					this.Onb_cotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_cot", DbType="Float")]
		public System.Nullable<double> h_cot
		{
			get
			{
				return this._h_cot;
			}
			set
			{
				if ((this._h_cot != value))
				{
					this.Onh_cotChanging(value);
					this.SendPropertyChanging();
					this._h_cot = value;
					this.SendPropertyChanged("h_cot");
					this.Onh_cotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_dai", DbType="Float")]
		public System.Nullable<double> h_dai
		{
			get
			{
				return this._h_dai;
			}
			set
			{
				if ((this._h_dai != value))
				{
					this.Onh_daiChanging(value);
					this.SendPropertyChanging();
					this._h_dai = value;
					this.SendPropertyChanged("h_dai");
					this.Onh_daiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bdai", DbType="Float")]
		public System.Nullable<double> Bdai
		{
			get
			{
				return this._Bdai;
			}
			set
			{
				if ((this._Bdai != value))
				{
					this.OnBdaiChanging(value);
					this.SendPropertyChanging();
					this._Bdai = value;
					this.SendPropertyChanged("Bdai");
					this.OnBdaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ldai", DbType="Float")]
		public System.Nullable<double> Ldai
		{
			get
			{
				return this._Ldai;
			}
			set
			{
				if ((this._Ldai != value))
				{
					this.OnLdaiChanging(value);
					this.SendPropertyChanging();
					this._Ldai = value;
					this.SendPropertyChanged("Ldai");
					this.OnLdaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
