#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_Hoa_Yambi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VuVanHoa_nenmong")]
	public partial class VuVanHoa_DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_lop_dat(tbl_lop_dat instance);
    partial void Updatetbl_lop_dat(tbl_lop_dat instance);
    partial void Deletetbl_lop_dat(tbl_lop_dat instance);
    partial void Inserttbl_betong(tbl_betong instance);
    partial void Updatetbl_betong(tbl_betong instance);
    partial void Deletetbl_betong(tbl_betong instance);
    #endregion
		
		public VuVanHoa_DatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VuVanHoa_nenmongConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VuVanHoa_DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_lop_dat> tbl_lop_dats
		{
			get
			{
				return this.GetTable<tbl_lop_dat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_betong> tbl_betongs
		{
			get
			{
				return this.GetTable<tbl_betong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_cot_thep> tbl_cot_theps
		{
			get
			{
				return this.GetTable<tbl_cot_thep>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lop_dat")]
	public partial class tbl_lop_dat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lop_dat;
		
		private string _MaLopDat;
		
		private System.Nullable<double> _chieuday;
		
		private System.Nullable<byte> _n;
		
		private string _loaidat;
		
		private string _trangthai;
		
		private System.Nullable<double> _dungtrongrieng;
		
		private System.Nullable<int> _modundanhoi;
		
		private System.Nullable<int> _gocmasat;
		
		private System.Nullable<int> _doroi;
		
		private System.Nullable<int> _suckhangxuyen;
		
		private System.Nullable<int> _is_delete;
		
		private System.Nullable<double> _k;
		
		private System.Nullable<double> _alpha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lop_datChanging(int value);
    partial void Onid_lop_datChanged();
    partial void OnMaLopDatChanging(string value);
    partial void OnMaLopDatChanged();
    partial void OnchieudayChanging(System.Nullable<double> value);
    partial void OnchieudayChanged();
    partial void OnnChanging(System.Nullable<byte> value);
    partial void OnnChanged();
    partial void OnloaidatChanging(string value);
    partial void OnloaidatChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OndungtrongriengChanging(System.Nullable<double> value);
    partial void OndungtrongriengChanged();
    partial void OnmodundanhoiChanging(System.Nullable<int> value);
    partial void OnmodundanhoiChanged();
    partial void OngocmasatChanging(System.Nullable<int> value);
    partial void OngocmasatChanged();
    partial void OndoroiChanging(System.Nullable<int> value);
    partial void OndoroiChanged();
    partial void OnsuckhangxuyenChanging(System.Nullable<int> value);
    partial void OnsuckhangxuyenChanged();
    partial void Onis_deleteChanging(System.Nullable<int> value);
    partial void Onis_deleteChanged();
    partial void OnkChanging(System.Nullable<double> value);
    partial void OnkChanged();
    partial void OnalphaChanging(System.Nullable<double> value);
    partial void OnalphaChanged();
    #endregion
		
		public tbl_lop_dat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lop_dat", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_lop_dat
		{
			get
			{
				return this._id_lop_dat;
			}
			set
			{
				if ((this._id_lop_dat != value))
				{
					this.Onid_lop_datChanging(value);
					this.SendPropertyChanging();
					this._id_lop_dat = value;
					this.SendPropertyChanged("id_lop_dat");
					this.Onid_lop_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopDat", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLopDat
		{
			get
			{
				return this._MaLopDat;
			}
			set
			{
				if ((this._MaLopDat != value))
				{
					this.OnMaLopDatChanging(value);
					this.SendPropertyChanging();
					this._MaLopDat = value;
					this.SendPropertyChanged("MaLopDat");
					this.OnMaLopDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chieuday", DbType="Float")]
		public System.Nullable<double> chieuday
		{
			get
			{
				return this._chieuday;
			}
			set
			{
				if ((this._chieuday != value))
				{
					this.OnchieudayChanging(value);
					this.SendPropertyChanging();
					this._chieuday = value;
					this.SendPropertyChanged("chieuday");
					this.OnchieudayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n", DbType="TinyInt")]
		public System.Nullable<byte> n
		{
			get
			{
				return this._n;
			}
			set
			{
				if ((this._n != value))
				{
					this.OnnChanging(value);
					this.SendPropertyChanging();
					this._n = value;
					this.SendPropertyChanged("n");
					this.OnnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaidat", DbType="NVarChar(50)")]
		public string loaidat
		{
			get
			{
				return this._loaidat;
			}
			set
			{
				if ((this._loaidat != value))
				{
					this.OnloaidatChanging(value);
					this.SendPropertyChanging();
					this._loaidat = value;
					this.SendPropertyChanged("loaidat");
					this.OnloaidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dungtrongrieng", DbType="Float")]
		public System.Nullable<double> dungtrongrieng
		{
			get
			{
				return this._dungtrongrieng;
			}
			set
			{
				if ((this._dungtrongrieng != value))
				{
					this.OndungtrongriengChanging(value);
					this.SendPropertyChanging();
					this._dungtrongrieng = value;
					this.SendPropertyChanged("dungtrongrieng");
					this.OndungtrongriengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modundanhoi", DbType="Int")]
		public System.Nullable<int> modundanhoi
		{
			get
			{
				return this._modundanhoi;
			}
			set
			{
				if ((this._modundanhoi != value))
				{
					this.OnmodundanhoiChanging(value);
					this.SendPropertyChanging();
					this._modundanhoi = value;
					this.SendPropertyChanged("modundanhoi");
					this.OnmodundanhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gocmasat", DbType="Int")]
		public System.Nullable<int> gocmasat
		{
			get
			{
				return this._gocmasat;
			}
			set
			{
				if ((this._gocmasat != value))
				{
					this.OngocmasatChanging(value);
					this.SendPropertyChanging();
					this._gocmasat = value;
					this.SendPropertyChanged("gocmasat");
					this.OngocmasatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doroi", DbType="Int")]
		public System.Nullable<int> doroi
		{
			get
			{
				return this._doroi;
			}
			set
			{
				if ((this._doroi != value))
				{
					this.OndoroiChanging(value);
					this.SendPropertyChanging();
					this._doroi = value;
					this.SendPropertyChanged("doroi");
					this.OndoroiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suckhangxuyen", DbType="Int")]
		public System.Nullable<int> suckhangxuyen
		{
			get
			{
				return this._suckhangxuyen;
			}
			set
			{
				if ((this._suckhangxuyen != value))
				{
					this.OnsuckhangxuyenChanging(value);
					this.SendPropertyChanging();
					this._suckhangxuyen = value;
					this.SendPropertyChanged("suckhangxuyen");
					this.OnsuckhangxuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_delete", DbType="Int")]
		public System.Nullable<int> is_delete
		{
			get
			{
				return this._is_delete;
			}
			set
			{
				if ((this._is_delete != value))
				{
					this.Onis_deleteChanging(value);
					this.SendPropertyChanging();
					this._is_delete = value;
					this.SendPropertyChanged("is_delete");
					this.Onis_deleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k", DbType="Float")]
		public System.Nullable<double> k
		{
			get
			{
				return this._k;
			}
			set
			{
				if ((this._k != value))
				{
					this.OnkChanging(value);
					this.SendPropertyChanging();
					this._k = value;
					this.SendPropertyChanged("k");
					this.OnkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha", DbType="Float")]
		public System.Nullable<double> alpha
		{
			get
			{
				return this._alpha;
			}
			set
			{
				if ((this._alpha != value))
				{
					this.OnalphaChanging(value);
					this.SendPropertyChanging();
					this._alpha = value;
					this.SendPropertyChanged("alpha");
					this.OnalphaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_betong")]
	public partial class tbl_betong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_betong;
		
		private string _mabetong;
		
		private string _tenbetong;
		
		private System.Nullable<double> _rb;
		
		private System.Nullable<double> _rbt;
		
		private System.Nullable<double> _eb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_betongChanging(int value);
    partial void Onid_betongChanged();
    partial void OnmabetongChanging(string value);
    partial void OnmabetongChanged();
    partial void OntenbetongChanging(string value);
    partial void OntenbetongChanged();
    partial void OnrbChanging(System.Nullable<double> value);
    partial void OnrbChanged();
    partial void OnrbtChanging(System.Nullable<double> value);
    partial void OnrbtChanged();
    partial void OnebChanging(System.Nullable<double> value);
    partial void OnebChanged();
    #endregion
		
		public tbl_betong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_betong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_betong
		{
			get
			{
				return this._id_betong;
			}
			set
			{
				if ((this._id_betong != value))
				{
					this.Onid_betongChanging(value);
					this.SendPropertyChanging();
					this._id_betong = value;
					this.SendPropertyChanged("id_betong");
					this.Onid_betongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabetong", DbType="VarChar(35)")]
		public string mabetong
		{
			get
			{
				return this._mabetong;
			}
			set
			{
				if ((this._mabetong != value))
				{
					this.OnmabetongChanging(value);
					this.SendPropertyChanging();
					this._mabetong = value;
					this.SendPropertyChanged("mabetong");
					this.OnmabetongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbetong", DbType="VarChar(35)")]
		public string tenbetong
		{
			get
			{
				return this._tenbetong;
			}
			set
			{
				if ((this._tenbetong != value))
				{
					this.OntenbetongChanging(value);
					this.SendPropertyChanging();
					this._tenbetong = value;
					this.SendPropertyChanged("tenbetong");
					this.OntenbetongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rb", DbType="Float")]
		public System.Nullable<double> rb
		{
			get
			{
				return this._rb;
			}
			set
			{
				if ((this._rb != value))
				{
					this.OnrbChanging(value);
					this.SendPropertyChanging();
					this._rb = value;
					this.SendPropertyChanged("rb");
					this.OnrbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rbt", DbType="Float")]
		public System.Nullable<double> rbt
		{
			get
			{
				return this._rbt;
			}
			set
			{
				if ((this._rbt != value))
				{
					this.OnrbtChanging(value);
					this.SendPropertyChanging();
					this._rbt = value;
					this.SendPropertyChanged("rbt");
					this.OnrbtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eb", DbType="Float")]
		public System.Nullable<double> eb
		{
			get
			{
				return this._eb;
			}
			set
			{
				if ((this._eb != value))
				{
					this.OnebChanging(value);
					this.SendPropertyChanging();
					this._eb = value;
					this.SendPropertyChanged("eb");
					this.OnebChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cot_thep")]
	public partial class tbl_cot_thep
	{
		
		private System.Nullable<int> _IDCotThep;
		
		private string _MaCotThep;
		
		private string _TenCotThep;
		
		private System.Nullable<double> _Rs;
		
		private System.Nullable<double> _Rsc;
		
		private System.Nullable<double> _Es;
		
		public tbl_cot_thep()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCotThep", DbType="Int")]
		public System.Nullable<int> IDCotThep
		{
			get
			{
				return this._IDCotThep;
			}
			set
			{
				if ((this._IDCotThep != value))
				{
					this._IDCotThep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCotThep", DbType="VarChar(35)")]
		public string MaCotThep
		{
			get
			{
				return this._MaCotThep;
			}
			set
			{
				if ((this._MaCotThep != value))
				{
					this._MaCotThep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCotThep", DbType="VarChar(35)")]
		public string TenCotThep
		{
			get
			{
				return this._TenCotThep;
			}
			set
			{
				if ((this._TenCotThep != value))
				{
					this._TenCotThep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rs", DbType="Float")]
		public System.Nullable<double> Rs
		{
			get
			{
				return this._Rs;
			}
			set
			{
				if ((this._Rs != value))
				{
					this._Rs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rsc", DbType="Float")]
		public System.Nullable<double> Rsc
		{
			get
			{
				return this._Rsc;
			}
			set
			{
				if ((this._Rsc != value))
				{
					this._Rsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Es", DbType="Float")]
		public System.Nullable<double> Es
		{
			get
			{
				return this._Es;
			}
			set
			{
				if ((this._Es != value))
				{
					this._Es = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
